website/views.py
from flask import Blueprint, render_template, request, flash, jsonify, redirect, url_for
from .models import Product, Order, OrderItem, Customer
from . import db
import json
from sqlalchemy import create_engine, MetaData, Table, Column, Integer, String


views = Blueprint('views', __name__)


############################ CUSTOMER VIEWS##############################################

# customer list


@views.route('/customer', methods=['GET', 'POST'])
def customer():
    result = Customer.query.all()

    return render_template("customer.html", result=result)

# Add customer


@views.route('/add_customer', methods=['GET', 'POST'])
def add_customer():
    if request.method == 'POST':
        customerName = request.form.get('customerName')
        contactNum = request.form.get('contactNum')
        address = request.form.get('address')
        email = request.form.get('email')

        new_customer = Customer(
            name=customerName, contactNum=contactNum, address=address, email=email)

        db.session.add(new_customer)
        db.session.commit()

        flash('New Customer Added', category='success')
        return redirect(url_for('views.customer'))

    return render_template("new_customer.html")

# edit customer


@views.route('/edit_customer/<int:id>', methods=['GET', 'POST'])
def edit_customer(id):
    name_to_update = Customer.query.get_or_404(id)
    if request.method == "POST":
        name_to_update.name = request.form.get('customerName')
        name_to_update.contactNum = request.form.get('contactNum')
        name_to_update.address = request.form.get('address')
        name_to_update.email = request.form.get('email')
        try:
            db.session.commit()
            flash('User Updated Successfuly', category='success')
            return redirect(url_for('views.customer'))
        except:
            print("Here")
            flash('Error! Looks like there was a problem', category="error")
            return redirect(url_for('views.customer'))

    else:
        return render_template("edit_customer.html", name_to_update=name_to_update)


# delete customer
@views.route('/delete-customer', methods=["POST"])
def delete_customer():
    customer = json.loads(request.data)
    customerId = customer['rowId']
    customer = Customer.query.get(customerId)
    if customer:
        db.session.delete(customer)
        db.session.commit()

    return jsonify({})


################################## PRODUCT VIEWS#######################################

# product list
@views.route('/product_list', methods=['GET', 'POST'])
def productList():
    result = Product.query.all()

    return render_template("product_list.html", result=result)

# new product


@views.route('/new_product', methods=['GET', 'POST'])
def new_product():
    if request.method == 'POST':
        name = request.form.get('productName')
        price = request.form.get('price')
        description = request.form.get('description')

        new_product = Product(
            name=name, price=price, description=description)

        db.session.add(new_product)
        db.session.commit()

        flash('New Product Added', category='success')
        return redirect(url_for('views.productList'))

    return render_template("new_product.html")

# edit product


@views.route('/edit_product/<int:id>', methods=['GET', 'POST'])
def edit_product(id):
    product_to_update = Product.query.get_or_404(id)
    if request.method == "POST":
        product_to_update.name = request.form.get('productName')
        product_to_update.price = request.form.get('price')
        product_to_update.description = request.form.get('description')
        try:
            db.session.commit()
            flash('Product Updated Successfuly', category='success')
            return redirect(url_for('views.productList'))
        except:
            flash('Error! Looks like there was a problem', category="error")
            return redirect(url_for("views.productList"))

    else:
        return render_template("edit_product.html", product_to_update=product_to_update)


# delete product
@views.route('/delete-product', methods=["POST"])
def delete_product():
    product = json.loads(request.data)
    productID = product['rowId']
    product = Product.query.get(productID)
    if product:
        db.session.delete(product)
        db.session.commit()

    return jsonify({})

#################################### ORDER VIEWS #######################################


@views.route('/new_order')
def new_order_redir():
    try:
        newest_order = Order.query.order_by(Order.orderID.desc()).first()
        return redirect(url_for('views.new_order', orderID=newest_order.orderID+1))
    except AttributeError:
        return redirect(url_for('views.new_order', orderID=1))


# add new item to order


@views.route('/new_order/<int:orderID>', methods=['GET', 'POST'])
def new_order(orderID):
    productList = Product.query.all()
    # orderItemList = OrderItem.query.filter(OrderItem.orderID == orderID).all()
    exists = Order.query.get(orderID)

    if not exists:
        exists = Order(orderID=orderID, totalPrice=0)

        db.session.add(exists)
        db.session.commit()

    if request.method == "POST":
        # create orderItem
        productID = request.form.get('productItemID')
        qty = request.form.get('qty')

        product_in_order = OrderItem.query.filter_by(
            productID=productID, orderID=orderID).first()
        if (product_in_order):

            product_in_order.qty = qty
            db.session.commit()

            flash('Product Quantity Edited', category='success')

        else:

            new_orderItem = OrderItem(
                productID=productID, qty=qty, orderID=exists.orderID)

            db.session.add(new_orderItem)
            db.session.commit()

            flash('New Product Added', category='success')

        # computing total price of orders
        total = 0
        for items in exists.orderItem:
            total = total + items.product.price * items.qty

        exists.totalPrice = total
        db.session.commit()

        # return render_template("new_order.html", orderID=orderID, orderItemID=orderItemID, productList=productList)
        return render_template("new_order.html", exists=exists, productList=productList)

    # computing total price of orders
    total = 0
    for items in exists.orderItem:
        total = total + items.product.price*items.qty

    exists.totalPrice = total
    db.session.commit()

    return render_template("new_order.html", exists=exists, productList=productList)

# delete orderItem


@views.route('/delete-orderItem', methods=["POST"])
def delete_orderItem():
    orderItem = json.loads(request.data)
    orderItemID = orderItem['orderItemID']
    orderItem = OrderItem.query.get(orderItemID)
    print(orderItem)
    if orderItem:
        db.session.delete(orderItem)
        db.session.commit()

    return jsonify({})

############################### SALES LIST ##########################
# sales list


@views.route('/', methods=['GET', 'POST'])
def sales_list():
    sales = Order.query.all()
    productList = Product.query.all()
    itemList = OrderItem.query.all()

    # values for number of orders
    total_orders = 0
    for row in sales:
        total_orders = total_orders + 1

    # Sales revenue

    return render_template("sales_list.html", sales=sales, total_orders=total_orders, productList=productList, itemList=itemList)

# finish order


@views.route('/finish_order/<int:orderID>')
def finish_order(orderID):
    # deletes order if empty
    finishOrder = Order.query.get(orderID)
    print(finishOrder.orderItem)
    if not finishOrder.orderItem:
        db.session.delete(finishOrder)
        db.session.commit()

    return redirect(url_for('views.sales_list'))


@views.route('/delete_order/<int:orderID>')
def delete_order(orderID):
    # deletes order if empty
    deleteOrder = Order.query.get(orderID)
    db.session.delete(deleteOrder)
    db.session.commit()

    return redirect(url_for('views.sales_list'))

website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />

    <script
      type="text/javascript"
      src="{{url_for('static', filename='index.js') }}"
    ></script>

    <title>{% block title %}Home{% endblock %}</title>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          <a class="nav-item nav-link" id="Add Sales" href="/">Sales</a>
          <a class="nav-item nav-link" id="Customer List" href="/customer"
            >Customer List</a
          >
          <a class="nav-item nav-link" id="Product List" href="/product_list"
            >Product List</a
          >
          <a class="nav-item nav-link" id="Product List" href="/new_order"
            >New Order</a
          >
        </div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>

    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

website/templates/customer.html
{% extends "base.html"%} {% block title%}Customer List{% endblock%} {% block
content %}
</br>
<h1 align="center">Customer</h1>
</br>
<ul class="list-group list-group-flush" id="customer">
  <div class="table-responsive">
    <table class="table table-striped table-sm">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Contact Number</th>
        <th>Address</th>
        <th>Email</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>

      {% for row in result %}
      <tr>
        <td>{{row.customerID }}</td>
        <td>{{row.name }}</td>
        <td>{{row.contactNum }}</td>
        <td>{{row.address }}</td>
        <td>{{row.email}}</td>
        <td>
          <button
            button
            class="btn btn-success btn-sm rounded-0"
            type="button"
            data-toggle="tooltip"
            data-placement="top"
            title="Edit"
            onclick="window.location.href='{{url_for('views.edit_customer', id=row.customerID)}}'"
          >
            <i class="fa fa-edit"></i>
          </button>
        </td>

        <td>
          <button
            class="btn btn-danger btn-sm rounded-0"
            type="button"
            data-toggle="tooltip"
            data-placement="top"
            title="Delete"
            onClick="deleteCustomer({{ row.customerID }})"
          >
            <i class="fa fa-trash"></i>
          </button>
        </td>
      </tr>
      {%endfor%}
    </table>
  </div>
</ul>

<br />
<div align="center">
  <button
    type="newCustomer_button"
    class="btn btn-primary"
    onClick="window.location.href = 'add_customer';"
  >
    Add Customer
  </button>
</div>

{% endblock %}

website/templates/edit_customer.html
{% extends "base.html"%} {% block title%}Edit Customer{% endblock%} {% block
content %}

<form action="/edit_customer/{{name_to_update.customerID}}" method="POST">
  <h3 align="center">Edit Customer</h3>

  <div class="form-group">
    <label for="customerName">Customer Name</label>
    <input
      type="text"
      class="form-control"
      value="{{name_to_update.name}}"
      id="customerName"
      name="customerName"
      placeholder="Enter Customer Name"
    />
  </div>

  <div class="form-group">
    <label for="contactNum">Customer Contact Number</label>
    <input
      type="tel"
      class="form-control"
      value="{{name_to_update.contactNum}}"
      id="contactNum"
      name="contactNum"
      placeholder="Enter Customer Contact Number"
      pattern="[0-9]{10}"
    />
  </div>

  <div class="form-group">
    <label for="address">Customer Address</label>
    <input
      type="text"
      class="form-control"
      value="{{name_to_update.address}}"
      id="address"
      name="address"
      placeholder="Enter Customer Address"
    />
  </div>

  <div class="form-group">
    <label for="email">Customer Email</label>
    <input
      type="text"
      class="form-control"
      value="{{name_to_update.email}}"
      id="email"
      name="email"
      placeholder="Enter Customer Email"
      pattern="^\S+@\S+$"
    />
    <br />
    <button type="submit" class="btn btn-primary">Submit</button>
  </div>
</form>

{% endblock %}

website/templates/edit_product.html
{% extends "base.html"%} {% block title%}Edit Prodcut{% endblock%} {% block
    content %}
    
    <form action="/edit_product/{{product_to_update.productID}}" method="POST">
      <h3 align="center">Edit Product</h3>
    
      <div class="form-group">
        <label for="productName">Product Name</label>
        <input
          type="text"
          class="form-control"
          value="{{product_to_update.name}}"
          id="productName"
          name="productName"
          placeholder="Enter Product Name"
        />
      </div>
    
      <div class="form-group">
        <label for="price">Price</label>
        <input
          type="number"
          min="0.01"
          step="0.01"
          class="form-control"
          value="{{product_to_update.price}}"
          id="price"
          name="price"
          placeholder="Enter Product Price"
        />
      </div>
    
      <div class="form-group">
        <label for="address">Product Description</label>
        <input
          type="text"
          class="form-control"
          value="{{product_to_update.description}}"
          id="description"
          name="description"
          placeholder="Enter Product Description"
        />
      </div>

      
        <br />
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </form>
    
    {% endblock %}
    

website/templates/new_customer.html
{% extends "base.html"%} {% block title%}New Customer{% endblock%} {% block
content %}

<form method="POST">
  <h3 align="center">New Customer</h3>

  <div class="form-group">
    <label for="customerName">Customer Name</label>
    <input
      type="text"
      class="form-control"
      id="customerName"
      name="customerName"
      placeholder="Enter Customer Name"
    />
  </div>

  <div class="form-group">
    <label for="contactNum">Customer Contact Number</label>
    <input
      type="tel"
      class="form-control"
      id="contactNum"
      name="contactNum"
      placeholder="Enter Customer Contact Number"
      pattern="[0-9]{10}"
    />
  </div>

  <div class="form-group">
    <label for="address">Customer Address</label>
    <input
      type="text"
      class="form-control"
      id="address"
      name="address"
      placeholder="Enter Customer Address"
    />
  </div>

  <div class="form-group">
    <label for="email">Customer Email</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter Customer Email"
      pattern="^\S+@\S+$"
    />
    <br />
    <button type="submit" class="btn btn-primary">Submit</button>
  </div>
</form>

{% endblock %}

website/templates/new_order.html
{% extends "base.html"%} {% block title%}New Order{% endblock%} {% block
    content %}
    <div>
    <form method="POST">
    </br>
      <h3 align="left">Order # {{exists.orderID}}</h3>
    </br>

      <div class="form-group">
        <label for="productItemID">Product Name</label>
        
        <select id="productItemID", name = "productItemID", class="form-control">
        {% for productItem in productList %}
        <option value="{{productItem.productID}}" >{{productItem.name}} &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp ${{productItem.price}}</option>
        {%endfor%}
        </select>
      </div>
    
      <div class="form-group">
        <label for="qty">Quantity</label>
        <input
          type="number"
          class="form-control"
          min="1"
          step="1"
          id="qty"
          name="qty"
          placeholder="Enter Product Quantity"
          required="required"
        />
      </div>
    
        <br />
        <button type="submit" class="btn btn-primary">Add Item</button>
      </div>
    </form>
  
    <br />
    <br />
  <ul class="list-group list-group-flush" id="product">
    <div class="table-responsive">
        <table class="table table-sm">
          <tr>
            <th>Order Item</th>
            <th>Qty</th>
            <th>Price</th>
            <th>Delete</th>
          </tr>
          
          {% for item in exists.orderItem %}
          <tr>
            <td>{{item.product.name }}</td>
            <td>{{item.qty }}</td>
            <td>{{item.product.price*item.qty}}</td>
  
            <td>
              <button
                class="btn btn-danger btn-sm rounded-0"
                type="button"
                data-toggle="tooltip"
                data-placement="top"
                title="Delete"
                onClick="deleteOrderItem({{ item.orderItemID }}, {{ exists.orderID }})"
              >
                <i class="fa fa-trash"></i>
              </button>
            </td>
          </tr>
          {%endfor%}

          <tr class = "table-primary">
            <td></td>
            <td>TOTAL</td>
            <td>{{exists.totalPrice}}</td>
          </tr>

        </table>

      <div align="center">
        <button
            button
            class="btn btn-success btn-sm rounded-0"
            type="button"
            data-toggle="tooltip"
            data-placement="top"
            onclick="window.location.href='{{url_for('views.finish_order', orderID = exists.orderID)}}'"
          >
          Finish Order
        </button>
      </div>

    </ul>
  </div>
    {% endblock %}
    

website/templates/new_product.html
{% extends "base.html"%} {% block title%}New Product{% endblock%} {% block
content %}

<form method="POST">
</br>
  <h3 align="center">New Product</h3>

  <div class="form-group">
    <label for="productName">Product Name</label>
    <input
      type="text"
      class="form-control"
      id="productName"
      name="productName"
      placeholder="Enter Product Name"
    />
  </div>

  <div class="form-group">
    <label for="price">Price</label>
    <input
      type="number"
      min="0.01"
      step="0.01"
      class="form-control"
      id="price"
      name="price"
      placeholder="Enter Product Price"
    />
  </div>

  <div class="form-group">
    <label for="address">Product Description</label>
    <input
      type="text"
      class="form-control"
      id="description"
      name="description"
      placeholder="Enter Product Description"
    />
  </div>

  <br />
  <button type="submit" class="btn btn-primary">Submit</button>
</div>
</form>


  {% endblock %}
</form>

website/templates/product_list.html
{% extends "base.html"%} {% block title%}Product List{% endblock%} {% block
content %}
</br>
<h1 align="center">Product List</h1>
</br>
<ul class="list-group list-group-flush" id="product">
  <div class="table-responsive">
    <table class="table table-striped table-sm">

        <tr>
          <th>ID</th>
          <th>Product Name</th>
          <th>Price</th>
          <th>Description</th>
          <th>Edit</th>
          <th>Delete</th>
        </tr>

        {% for row in result %}
        <tr>
          <td>{{row.productID }}</td>
          <td>{{row.name }}</td>
          <td>{{row.price }}</td>
          <td>{{row.description }}</td>
          <td>
            <button
              button
              class="btn btn-success btn-sm rounded-0"
              type="button"
              data-toggle="tooltip"
              data-placement="top"
              title="Edit"
              onclick="window.location.href='{{url_for('views.edit_product', id=row.productID)}}'"
            >
              <i class="fa fa-edit"></i>
            </button>
          </td>

          <td>
            <button
              class="btn btn-danger btn-sm rounded-0"
              type="button"
              data-toggle="tooltip"
              data-placement="top"
              title="Delete"
              onClick="deleteProduct({{ row.productID }})"
            >
              <i class="fa fa-trash"></i>
            </button>
          </td>
        </tr>
        {%endfor%}

    </table>
  </div>
</ul>

<br />
<div align="center">
  <button
    type="newProduct_button"
    class="btn btn-primary"
    onClick="window.location.href = 'new_product';"
  >
    Add Product
  </button>
</div>

{% endblock %}

website/templates/sales_list.html
{% extends "base.html"%} {% block title%}Sales List{% endblock%} {% block
    content %}
</br>
<h3 align="left">Sales List</h1>
</br>
  <ul class="list-group list-group-flush" id="product">
    <div class="table-responsive">
      <table class="table table-striped table-sm">

        <tr>
          <th>ID</th>
          <th>Order Details</th>
          <th>Qty</th>
          <th>Price</th>
          <th>Edit</th>
          <th>Delete</th>
        </tr>
        {% set total_revenue = namespace(total = 0.0) %}
        {% for row in sales %}
        <tr>
          <td>{{row.orderID }}</td>
          <td>
            {%for items in row.orderItem%}
            {{items.product.name }} <br>
            {%endfor%}
            Total
          </td>
          <td>
            {%for items in row.orderItem%}
            {{items.qty }} <br>
            {%endfor%}
          </td>
          <td>
            {%for items in row.orderItem%}
            {{items.product.price*items.qty }} <br>
            {%endfor%}
            {{row.totalPrice}} <br>
            {% set total_revenue.total = total_revenue.total + row.totalPrice%} 
          </td>
            <td>
              <button
                button
                class="btn btn-success btn-sm rounded-0"
                type="button"
                data-toggle="tooltip"
                data-placement="top"
                title="Edit"
                onclick="window.location.href='{{url_for('views.new_order', orderID=row.orderID)}}'"
              >
                <i class="fa fa-edit"></i>
              </button>
            </td>
  
            <td>
              <button
                class="btn btn-danger btn-sm rounded-0"
                type="button"
                data-toggle="tooltip"
                data-placement="top"
                title="Delete"
                onclick="window.location.href='{{url_for('views.delete_order', orderID = row.orderID)}}'"
              >
                <i class="fa fa-trash"></i>
              </button>
            </td>
          </tr>
          {%endfor%}
  
      </table>
    </div>
  </ul>
  
  <br />
  <div align="left">
    <button
      type="newOrder_button"
      class="btn btn-primary"
      onClick="window.location.href = 'new_order';"
    >
      Add New Order
    </button>
  </div>

</br>
</br>
  <ul class="list-group list-group-flush" id="product">
    <div class="table-responsive">
      <table class="table table-sm table-bordered">

        <tr>
          <th>Sales Summary</th>
          <th></th>
        </tr>

        <tr>
          <td>Number of Orders</td>
          <td>
            {{total_orders}}
          </td>
        </tr>

          <tr>
            <td>Sales Revenue</td>
            <td>${{total_revenue.total}}</td>
          </tr>
  
      </table>
    </div>
  </ul>
    
    {% endblock %}
    